name: it_center_mobile
description: IT Center Staff Authentication Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Authentication
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # UI Components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # Forms & Validation
  form_builder_validators: ^9.1.0
  flutter_form_builder: ^9.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Utils
  intl: ^0.19.0
  logger: ^2.0.2+1
  
  # Biometrics & Security
  local_auth: ^2.1.7
  
  # QR Code (for MFA)
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  
  # Permissions
  permission_handler: ^11.2.0
  
  # Image handling
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
